import os

MONGO_URI = os.environ.get("CODEFLOW_MONGO_URI")
SECRET_KEY = os.environ.get("CODEFLOW_SECRET_KEY")

RECAPTCHA_USE_SS = os.environ.get("CODEFLOW_CHECKBOX_RECAPTCHA_USE_SSL")
RECAPTCHA_PUBLIC_KEY = os.environ.get(
    "CODEFLOW_CHECKBOX_RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = os.environ.get(
    "CODEFLOW_CHECKBOX_RECAPTCHA_PRIVATE_KEY")
RECAPTCHA_OPTIONS = os.environ.get("CODEFLOW_CHECKBOX_RECAPTCHA_OPTIONS")
